name: benfy
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/sofia_pro/Sofia Pro Regular Az.otf
        - asset: assets/fonts/sofia_pro/Sofia Pro Bold Az.otf
          weight: 700
        - asset: assets/fonts/sofia_pro/Sofia Pro Light Az.otf
          weight: 300
        - asset: assets/fonts/sofia_pro/Sofia Pro Medium Az.otf
          weight: 500
        - asset: assets/fonts/sofia_pro/Sofia Pro Black Az.otf
          weight: 900
        - asset: assets/fonts/sofia_pro/Sofia Pro UltraLight Az.otf
          weight: 100
        - asset: assets/fonts/sofia_pro/Sofia Pro Regular Italic Az.otf
          style: italic
        - asset: assets/fonts/sofia_pro/Sofia Pro Bold Italic Az.otf
          weight: 700
          style: italic
